---

- name: Create Components Dirctory
  ansible.builtin.file:
    path: "{{ component_path }}"
    state: directory
    mode: '0755'
    recurse: true

- name: Downloading cfssl {{ cfssl_version }}
  ansible.builtin.get_url:
    url: "{{ download_location_prefix['cfssl'] }}/{{ cfssl_version|replace('v','') }}/{{ item }}_{{ cfssl_version|replace('v','') }}_linux_{{ arch_alias }}"
    dest: "{{ component_path }}/{{ item }}_{{ cfssl_version|replace('v','') }}_linux_{{ arch_alias }}"
    mode: '0755'
    timeout: 60
  loop: 
    - cfssl
    - cfssljson
  retries: 5
  delay: 10

- name: Downloading etcd {{ etcd_version }}
  ansible.builtin.get_url:
    url: "{{ download_location_prefix['etcd'] }}/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-{{ arch_alias }}.tar.gz"
    dest: "{{ component_path }}/etcd-{{ etcd_version }}-linux-{{ arch_alias }}.tar.gz"
    mode: '0755'
    timeout: 60
  retries: 5
  delay: 10

- name: Downloading Containerd {{ containerd_version }}
  ansible.builtin.get_url:
    url: "{{ download_location_prefix['containerd'] }}/{{ containerd_version }}/containerd-{{ containerd_version|replace('v', '') }}-linux-{{ arch_alias }}.tar.gz"
    dest: "{{ component_path }}/containerd-{{ containerd_version|replace('v', '') }}-linux-{{ arch_alias }}.tar.gz"
    mode: '0755'
    timeout: 60
  retries: 5
  delay: 10

- name: Downloading CNI Plugins {{ cni_version }}
  ansible.builtin.get_url:
    url: "{{ download_location_prefix['cni-plugins'] }}/{{ cni_version }}/cni-plugins-linux-{{ arch_alias }}-{{ cni_version }}.tgz"
    dest: "{{ component_path }}/cni-plugins-linux-{{ arch_alias }}-{{ cni_version }}.tgz" 
    mode: '0755'  
    timeout: 60
  retries: 5
  delay: 10

- name: Downloading runc {{ runc_version }}
  ansible.builtin.get_url:
    url: "{{ download_location_prefix['runc'] }}/{{ runc_version }}/runc.{{ arch_alias }}"
    dest: "{{ component_path }}/runc.{{ arch_alias }}"
    mode: '0755'
    timeout: 60
  retries: 5
  delay: 10

- name: Downloading Helm {{ helm_version }}
  ansible.builtin.get_url:
    url: "{{ download_location_prefix['helm'] }}/helm-{{ helm_version }}-linux-{{ arch_alias }}.tar.gz"
    dest: "{{ component_path }}/helm-{{ helm_version }}-linux-{{ arch_alias }}.tar.gz"
    mode: '0755'
    timeout: 60
  retries: 5
  delay: 10

- name: Downloading csi-driver-nfs {{ csi_nfs_version }} Chart
  ansible.builtin.get_url:
    url: "{{ download_location_prefix['csi-driver-nfs'] }}/{{ csi_nfs_version }}/csi-driver-nfs-{{ csi_nfs_version | replace('v', '') }}.tgz"
    dest: "{{ component_path }}/csi-driver-nfs-{{ csi_nfs_version | replace('v', '') }}.tgz"
    mode: '0755'
    timeout: 60
  retries: 5
  delay: 10

- name: Downloading Cilium {{ cilium_version }} Chart
  ansible.builtin.get_url:
    url: "{{ download_location_prefix['cilium'] }}/cilium-{{ cilium_version| replace('v', '') }}.tgz"
    dest: "{{ component_path }}/cilium-{{ cilium_version| replace('v', '') }}.tgz"
    mode: '0755'
    timeout: 60
  retries: 5
  delay: 10

- name: Downloading tigera-operator {{ calico_version }} Chart 
  ansible.builtin.get_url:
    url: "{{ download_location_prefix['tigera-operator'] }}/{{ calico_version }}/tigera-operator-{{ calico_version }}.tgz"
    dest: "{{ component_path }}/tigera-operator-{{ calico_version }}.tgz"
    mode: '0755'
    timeout: 60
  retries: 5
  delay: 10

- name: Downloading ingress-nginx {{ ingress_nginx_version }}
  ansible.builtin.get_url:
    url: "{{ download_location_prefix['ingress-nginx'] }}"
    dest: "{{ component_path }}/ingress-nginx-{{ ingress_nginx_version }}.yaml"
    mode: '0755'
    timeout: 60
  retries: 5
  delay: 10

