apiVersion: v1
kind: Service
metadata:
  name: nacos
  namespace: "{{ middware_namespace }}"
  labels:
    app: nacos
spec:
  ports:
    - name: client
      protocol: TCP
      port: 8848
      targetPort: 8848
    - name: rpc
      protocol: TCP
      port: 7848
      targetPort: 7848
    - name: new-rpc
      protocol: TCP
      port: 9848
      targetPort: 9848
  selector:
    app: nacos
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: nacos-nodeport
  namespace: "{{ middware_namespace }}"
spec:
  ports:
    - name: nacos-0-tcp-external
      protocol: TCP
      port: 8848
      targetPort: 8848
      nodePort: 38848
    - name: nacos-1-tcp-external
      protocol: TCP
      port: 7848
      targetPort: 7848
      nodePort: 37848
    - name: nacos-2-tcp-external
      protocol: TCP
      port: 9848
      targetPort: 9848
      nodePort: 39848
  selector:
    app: nacos
  type: NodePort

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
  namespace: "{{ middware_namespace }}"
  labels:
    app: nacos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos
  serviceName: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
        - name: nacos
          image: reg.guideirai.online/base/nacos-server:{{nacos_version}}
          ports:
            - name: client
              containerPort: 8848
              protocol: TCP
            - name: rpc
              containerPort: 7848
              protocol: TCP
            - name: new-rpc
              containerPort: 9848
              protocol: TCP
          env:
            - name: PREFER_HOST_MODE
              value: hostname
            - name: EMBEDDED_STORAGE
              value: embedded
            # - name: MYSQL_SERVICE_HOST
            #   value: mysql8."{{ middware_namespace }}".svc.cluster.local 
            # - name: MYSQL_SERVICE_PORT
            #   value: 3306
            - name: MODE
              value: standalone
            # - name: NACOS_AUTH_ENABLE
            #   value: 'false'
            # - name: PREFER_HOST_MODE
            #   value: hostname
            # - name: EMBEDDED_STORAGE
            #   value: embedded
            # - name: MODE
            #   value: standalone
            - name: NACOS_AUTH_ENABLE
              value: 'true'
            - name: NACOS_AUTH_IDENTITY_KEY
              value: nacos
            - name: NACOS_AUTH_IDENTITY_VALUE
              value: nacos
            - name: NACOS_AUTH_TOKEN
              value: 'NTgwMGIxZjE5MzdlYzg4YTA4NDlmYmNiYTZjZDQ4MGEgIC0K'
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
            - name: nacos-pvc
              mountPath: /home/nacos/data
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: regcred
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: nacos-pvc
        labels:
          app: nacos
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        volumeMode: Filesystem
 
---

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: nacos-local-pv
# spec:
#   capacity:
#     storage: 1Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Delete
#   local:
#     path: /mnt/data/nacos
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#         - matchExpressions:
#             - key: kubernetes.io/hostname
#               operator: In
#               values:
#                 - "{{ groups['schedulernode'] | random  }}"