apiVersion: apps/v1
kind: Deployment
metadata:
  name: powerjob-server
  namespace: "{{ middware_namespace }}"
  labels:
    app: powerjob-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: powerjob-server
  template:
    metadata:
      labels:
        app: powerjob-server
    spec:
      containers:
      - name: powerjob-server
        image: reg.guideirai.online/base/powerjob-server:{{powerjob_version}}
        ports:
        - containerPort: 7700
        - containerPort: 10086
        - containerPort: 10010
        env:
        - name: TZ
          value: 'Asia/Shanghai'
        - name: PARAMS
          #value: '--spring.profiles.active=product --spring.datasource.core.jdbc-url=jdbc:mysql://mysql8.{{ middware_namespace }}.svc.cluster.local:3306/powerjob-public?useUnicode=true&characterEncoding=UTF-8 --spring.datasource.core.username=root --spring.datasource.core.password=GSDT@gsdt002414'
          value: '--spring.profiles.active=product --spring.datasource.core.driver-class-name=dm.jdbc.driver.DmDriver --spring.datasource.core.jdbc-url=jdbc:dm://64.100.6.170:5236?schema=powerjob --spring.datasource.core.username=YJZH --spring.datasource.core.password=GDsk@#^!1 --spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.DmDialect --spring.jpa.database-platform=org.hibernate.dialect.DmDialect --spring.jpa.properties.hibernate.default_schema=powerjob --spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false'
      imagePullSecrets:
        - name: regcred

---
# service
apiVersion: v1
kind: Service
metadata:
  name: powerjob-server
  namespace: "{{ middware_namespace }}"
spec:
  selector:
    app: powerjob-server
  ports:
  - protocol: TCP
    port: 7700
    targetPort: 7700
    name: powerjob-server-0
  - protocol: TCP
    port: 10086
    targetPort: 10086
    name: powerjob-server-1
  - protocol: TCP
    port: 10010
    targetPort: 10010
    name: powerjob-server-2

---
# 服务nodeport
apiVersion: v1
kind: Service
metadata:
  name: powerjob-server-nodeport
  namespace: "{{ middware_namespace }}"
status:
  loadBalancer: {}
spec:
  ports:
    - protocol: TCP
      port: 7700
      targetPort: 7700
      nodePort: 37700
      name: powerjob-server-0-external
    - protocol: TCP
      port: 10086
      targetPort: 10086
      nodePort: 30086
      name: powerjob-server-1-external
    - protocol: TCP
      port: 10010
      targetPort: 30010
      name: powerjob-server-2-external
  selector:
    app: powerjob-server
  type: NodePort
