---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: tdengine-local-pv
# spec:
#   capacity:
#     storage: 5Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Delete
#   local:
#     path: /mnt/data/tdengine
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#         - matchExpressions:
#             - key: kubernetes.io/hostname
#               operator: In
#               values:
#                 - "{{ groups['schedulernode'] | random  }}"

---
apiVersion: v1
kind: Service
metadata:
  name: "tdengine"
  namespace: "{{ middware_namespace }}"
  labels:
    app: "tdengine"
spec:
  ports:
    - name: tcp6030
      protocol: "TCP"
      port: 6030
    - name: tcp6041
      protocol: "TCP"
      port: 6041
  selector:
    app: "tdengine"

---
apiVersion: v1
kind: Service
metadata:
  name: tdengine-nodeport
  namespace: "{{ middware_namespace }}"
spec:
  ports:
    - name: tdengine-0-tcp-external
      protocol: TCP
      port: 6030
      targetPort: 6030
      nodePort: 36030
    - name: tdengine-1-tcp-external
      protocol: TCP
      port: 6041
      targetPort: 6041
      nodePort: 36041
  selector:
    app: tdengine
  type: NodePort

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "tdengine"
  namespace: "{{ middware_namespace }}"
  labels:
    app: "tdengine"
spec:
  serviceName: "taosd"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: "tdengine"
  template:
    metadata:
      name: "tdengine"
      labels:
        app: "tdengine"
    spec:
      containers:
        - name: "tdengine"
          image: "reg.guideirai.online/base/tdengine:{{tdengine_version}}"
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: tcp6030
              protocol: "TCP"
              containerPort: 6030
            - name: tcp6041
              protocol: "TCP"
              containerPort: 6041
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVICE_NAME
              value: "taosd"
            - name: STS_NAME
              value: "tdengine"
            - name: STS_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: TZ
              value: "Asia/Shanghai"
            - name: TAOS_SERVER_PORT
              value: "6030"
            - name: TAOS_FIRST_EP
              value: "$(STS_NAME)-0.$(SERVICE_NAME).$(STS_NAMESPACE).svc.cluster.local:$(TAOS_SERVER_PORT)"
            - name: TAOS_FQDN
              value: "$(POD_NAME).$(SERVICE_NAME).$(STS_NAMESPACE).svc.cluster.local"
          volumeMounts:
            - name: tdengine-pvc
              mountPath: /var/lib/taos
          startupProbe:
            exec:
              command:
                - taos-check
            failureThreshold: 360
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - taos-check
            initialDelaySeconds: 5
            timeoutSeconds: 5000
          livenessProbe:
            exec:
              command:
                - taos-check
            initialDelaySeconds: 15
            periodSeconds: 20
      imagePullSecrets:
        - name: regcred
  volumeClaimTemplates:
    - metadata:
        name: tdengine-pvc
        namespace: "{{ middware_namespace }}"
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "5Gi"