
# - name: Ensure nfsmount.conf exists
#   ansible.builtin.lineinfile:
#     path: /etc/nfsmount.conf
#     line: "[ NFSMount_Global_Options ]"
#     create: yes
#     state: present

# - name: Update nfsmount.conf
#   ansible.builtin.blockinfile:
#     path: /etc/nfsmount.conf
#     insertafter: "[ NFSMount_Global_Options ]"
#     create: yes
#     block: |
#       retrans=5
#       acregmin=0
#       acregmax=0
#       acdirmin=0
#       acdirmax=0

- name: Check CSI Driver NFS {{ csi_nfs_version }} Helm Chart Exists
  ansible.builtin.stat:
    path: "{{ component_path }}/csi-driver-nfs-{{ csi_nfs_version }}.tgz"
  delegate_to: localhost
  run_once: true
  register: csi_stat

- name:  CSI Driver NFS {{ csi_nfs_version }} Offline File Not Exist
  ansible.builtin.fail:
    msg:  "{{ component_path }}/csi-driver-nfs-{{ csi_nfs_version }}.tgz not exists"
  when: not csi_stat.stat.exists and method == 'offline'


- name: Downloading CSI Driver NFS Helm Chart
  amazon.aws.s3_object:
    endpoint_url: "{{ s3_endpoint_url }}"
    access_key: "{{ s3_access_key }}"
    secret_key: "{{ s3_secret_key }}"
    bucket: "{{ s3_bucket_name }}"
    object: "csi-driver-nfs/csi-driver-nfs-{{ csi_nfs_version }}.tgz"
    dest: "{{ component_path }}/csi-driver-nfs-{{ csi_nfs_version }}.tgz"
    mode: get
    overwrite: different
  delegate_to: localhost
  run_once: true
  when: not csi_stat.stat.exists and method != 'offline'

- name: Copy CSI Driver NFS Helm Chart To Remote Host
  ansible.builtin.copy:
    src: "{{ component_path }}/csi-driver-nfs-{{ csi_nfs_version }}.tgz"
    dest: "/tmp/csi-driver-nfs-{{ csi_nfs_version }}.tgz"

- name: Copy CSI Driver NFS Values Override File
  ansible.builtin.template:
    src: "csi-driver-nfs-values-override.yaml.j2"
    dest: "/tmp/csi-driver-nfs-values-override.yaml"
    mode: '0644'

- name: Process Offline Image
  include_tasks: offline.yml
  when: method == 'offline'

- name: Install CSI Driver NFS
  ansible.builtin.shell: |
    helm upgrade --install csi-driver-nfs /tmp/csi-driver-nfs-{{ csi_nfs_version }}.tgz --namespace kube-system --values /tmp/csi-driver-nfs-values-override.yaml

      
- name: Transfor NFS YAML To Control
  ansible.builtin.template:
    src: nfs-server.yaml.j2
    dest: "{{ kubernetes_home }}/etc/nfs-server.yaml"
  when: nfs_server_address is not defined or nfs_server_address is none

- name: Install NFS Server
  ansible.builtin.shell: |
    kubectl apply -f {{ kubernetes_home }}/etc/nfs-server.yaml
  when: nfs_server_address is not defined or nfs_server_address is none