- name: Prepare cilium
  hosts: k8snode
  remote_user: root
  tasks:
    - name: Create cilium dirctory
      ansible.builtin.shell: |
        [[ -d ~/cilium ]] || mkdir ~/cilium

    - name: Copy cilium offline image to remote
      ansible.builtin.unarchive:
        src: "roles/cilium/files/cilium-images-{{ cilium_version }}-{{ansible_architecture}}.tar.gz"
        dest: "~/cilium/"

    - name: Load cilium offline image to containerd
      shell: |
        ls ~/cilium/*.tar|xargs -n 1 ctr -n k8s.io i import 
  tags: [ cilium ] 


- name: Deploy cilium
  hosts: k8smaster
  remote_user: root
  roles:
    - role: cilium
      tags: [ cilium ] 