
- name: System Init
  hosts: k8smaster,k8snode,etcd
  remote_user: root
  roles:
    - role: common
      tags: [ master, node, common ] 

 
- name: Install Etcd Cluster
  hosts: etcd
  remote_user: root
  roles:
    - role: etcd
      tags: [etcd]

- name: Install K8S Control Plane
  hosts: k8smaster
  remote_user: root
  roles:
    - role: kubernetes
      tags: [ master ] 

- name: Install K8S Worker
  hosts: k8snode
  remote_user: root
  roles:
    - role: kubernetes
      tags: [node]


- name: Cluster Settings
  hosts: k8smaster
  remote_user: root
  tasks:
    - name: Wait worker join to cluster
      ansible.builtin.wait_for:
        timeout: 30

    - name: Approve node sign request
      shell: |
        kubectl get csr|grep 'Pending'|awk '{print $1}'|xargs -n 1 kubectl certificate approve

    - name: Taint master
      shell: |
        kubectl taint nodes "{{ inventory_hostname }}" node-role.kubernetes.io/master=:NoSchedule
      when: allow_master_schedule != true
    
    - name: Label Control Plane
      shell: |
        kubectl label nodes "{{ inventory_hostname }}" node-role.kubernetes.io/control-plane=

  tags: node


# - name: Taint Master To NoSchedule
#   hosts: k8smaster
#   remote_user: root
#   tasks:
#     - name: Taint master
#       shell: |
#         kubectl taint nodes "{{ inventory_hostname }}" node-role.kubernetes.io/master=:NoSchedule
#       when: allow_master_schedule != true
#   tags: node