
- name: System Init
  hosts: k8smaster,k8snode,etcd
  remote_user: root
  roles:
    - role: common
      tags: [ master, node, common ] 

 
- name: Install Etcd Cluster
  hosts: etcd
  remote_user: root
  roles:
    - role: etcd
      tags: [etcd]

- name: Install K8S Master
  hosts: k8smaster
  remote_user: root
  roles:
    - role: kubernetes
      tags: [ master ] 

- name: Install K8S Node
  hosts: k8snode
  remote_user: root
  roles:
    - role: kubernetes
      tags: [node]


- name: Node Join To K8S Cluster
  hosts: k8smaster
  remote_user: root
  tasks:
    - name: Wait node join to cluster
      ansible.builtin.pause:
        seconds: 30

    - name: Approve node sign request
      shell: |
        kubectl get csr|grep 'Pending'|awk '{print $1}'|xargs -n 1 kubectl certificate approve
  tags: node


- name: Taint Master To NoSchedule
  hosts: k8smaster
  remote_user: root
  tasks:
    - name: Taint master
      shell: |
        kubectl taint nodes "{{ inventory_hostname }}" node-role.kubernetes.io/master=:NoSchedule
      when: allow_master_schedule != true
  tags: node