#!/bin/bash


case $1 in
    deploy)
    echo "deploy an kubernetes cluster"
    ;;
esac

# 生成客户端config文件
make_client_config(){
    # todo:
    """
    apiVersion: v1
    kind: Config
    current-context: default
    preferences: {}

    contexts:
    - name: default
      context:
      cluster: kubernetes
      user: kube-admin

    clusters:
    - name: kubernetes
    cluster:
        server: https://{{ control_ip }}:6443
        certificate-authority-data: <Base64-encoded-ca.pem>

    users:
    - name: kube-admin
    user:
        client-certificate-data: <Base64-encoded-kube-admin.pem>
        client-key-data: <Base64-encoded-kube-admin-key.pem>
    """
}
