
- name: Copy cilium tgz to remote
  copy:
    src: "{{role_path}}/files/cilium-{{cilium_version}}.tgz"
    dest: "~/cilium/"

- name: Install Cilium
  kubernetes.core.helm:
    chart_ref: "~/cilium/cilium-{{cilium_version}}.tgz"
    name: cilium
    chart_version: "{{cilium_version}}"
    wait: false
    # state: absent
    release_namespace: kube-system
    values:
      nodePort:
        enabled: true
      k8sServiceHost: "{{ansible_default_ipv4.address}}"
      k8sServicePort: "6443"
      kubeProxyReplacement: "true"
      bpf:
        lbExternalClusterIP: true
      # imagePullSecrets:
      #   - name: regcred
      operator:
        image:
          tag: "{{cilium_version}}"
          repository: reg.guideirai.online/cilium/operator
          useDigest: false
          suffix: ""
        replicas: 2
      image:
        repository: reg.guideirai.online/cilium/cilium
        tag: "{{cilium_version}}"
        useDigest: false
      ingressController:
        enabled: true
        default: true
        loadbalancerMode: shared
        service:
          type: NodePort
          # -- Configure a specific nodePort for insecure HTTP traffic on the shared LB service
          insecureNodePort: 30080
          # -- Configure a specific nodePort for secure HTTPS traffic on the shared LB service
          secureNodePort : 30443
        # hostNetwork:
        #   enabled: true
      # hubble:
      #   ui:
      #     enabled: true
      #   relay:
      #     enabled: true
      envoy:
        enabled: true
        image: 
          tag: v1.29.7
          repository: "reg.guideirai.online/cilium/cilium-envoy"
          useDigest: false
  when: ansible_distribution != 'Kylin Linux Advanced Server'


- name: Install Cilium-{{cilium_version}} in Kylin
  kubernetes.core.helm:
    chart_ref: "~/cilium/cilium-{{cilium_version}}.tgz"
    name: cilium
    chart_version: "{{cilium_version}}"
    wait: false
    # state: absent
    release_namespace: kube-system
    values:
      nodePort:
        enabled: true
      k8sServiceHost: "{{ansible_default_ipv4.address}}"
      k8sServicePort: "6443"
      kubeProxyReplacement: "strict"
      bpf:
        lbExternalClusterIP: true
      imagePullSecrets:
        - name: regcred
      operator:
        image:
          tag: "{{cilium_version}}"
          repository: reg.guideirai.online/cilium/operator
          useDigest: false
          suffix: ""
        replicas: 2
      image:
        repository: reg.guideirai.online/cilium/cilium
        tag: "{{cilium_version}}"
        useDigest: false
  when: ansible_distribution == 'Kylin Linux Advanced Server'

