---

- name: Copy Cilium Offline Images To Remote Host
  ansible.builtin.copy:
    src: "{{ image_path }}/cilium"
    dest: "/tmp/"
    mode: '0644'
  delegate_to: "{{ item }}"
  loop: "{{ groups['worker'] }}"

- name: Load Cilium Images
  ansible.builtin.shell: |
    ls /tmp/cilium/*.tar|xargs -n 1 ctr -n k8s.io i import
  delegate_to: "{{ item }}"
  loop: "{{ groups['worker'] }}"
  async: 3600
  poll: 0