calico_installation_registry: "{{ registry_mirror.get('docker.io', 'docker.io') }}"

pilot_download_url_prefix: 'https://dl.k8spilot.icu'
tigera_download_url_prefix: 'https://github.com/projectcalico/calico/releases/download'