- name: reload systemd
  shell: |
    systemctl daemon-reload

- name: start kube-apiserver
  systemd:
    name: kube-apiserver
    state: started
    enabled: yes

- name: start kube-controller-manager
  systemd:
    name: kube-controller-manager
    state: started
    enabled: yes

- name: start kube-scheduler
  systemd:
    name: kube-scheduler
    state: started
    enabled: yes

