---

- name: Set Architecture Alias
  set_fact:
    arch_alias: >-
      {% if ansible_architecture == 'x86_64' %}amd64{% elif ansible_architecture == 'aarch64' %}arm64{% else %}{{ ansible_architecture }}{% endif %}

- name: Downloading Kubernetes {{ kube_version }} Node Components
  ansible.builtin.get_url:
    url: "{{ download_location }}/kubernetes/{{ kube_version }}/linux/{{ arch_alias }}/{{ item }}"
    dest: "{{ kubernetes_home }}/bin/"
    mode: '0755'
    timeout: 60
  async: 6000
  poll: 10
  loop:
    - kubelet

- name: Downloading Containerd {{ containerd_version }}
  ansible.builtin.get_url:
    url: "{{ download_location }}/containerd/v{{ containerd_version }}/linux/{{ arch_alias }}/containerd-{{ containerd_version }}-linux-{{ arch_alias }}.tar.gz"
    dest: /tmp/
    mode: '0755'
    timeout: 60
  async: 6000
  poll: 10

- name: Downloading runc 
  ansible.builtin.get_url:
    url: "{{ download_location }}/runc/v1.3.0/linux/{{ arch_alias }}/runc.{{ arch_alias }}"
    dest: /tmp/
    mode: '0755'
    timeout: 60
  async: 6000
  poll: 10

- name: Downloading CNI plugins
  ansible.builtin.get_url:
    url: "{{ download_location }}/cni-plugins/{{ cni_version }}/linux/{{ arch_alias }}/cni-plugins-linux-{{ arch_alias }}-{{ cni_version }}.tgz"
    dest: /tmp/
    mode: '0755'
    timeout: 60
  async: 6000
  poll: 10

- name: Install Kernel Module Conf 
  copy:
    src: "cri.conf"
    dest: "/etc/modules-load.d/cri.conf"
    owner: root
    group: root
    mode: 0644

- name: Load Overlay and  Br_netfilter Module
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  with_items:
  - overlay
  - br_netfilter

- name: CRI Kernel Tuning
  ansible.posix.sysctl: 
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
  with_items: "{{ cri_kernel_params }}"


- name: Install Containerd With Plugins
  ansible.builtin.shell: |
    tar -xf /tmp/containerd-{{ containerd_version }}-linux-{{ arch_alias }}.tar.gz -C /usr/local/
    if [ ! -d "/opt/cni/bin" ]; then
      mkdir -p /opt/cni/bin
    fi
    tar --strip-components=1 -xf /tmp/cni-plugins-linux-{{ arch_alias }}-{{ cni_version }}.tgz -C /opt/cni/bin/
    mv /tmp/runc.{{ arch_alias }} /usr/local/sbin/runc
    chmod +x /usr/local/sbin/runc
    rm -f /tmp/containerd-{{ containerd_version }}-linux-{{ arch_alias }}.tar.gz /tmp/cni-plugins-linux-{{ arch_alias }}-{{ cni_version }}.tgz
  
- name: Install Node SSL Certificate And Token 
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0640
  with_items:
  - { src: "{{ pem_file_ca }}", dest: "{{ kubernetes_home }}/ssl/ca.pem" }
  - { src: "{{ pem_file_key }}", dest: "{{ kubernetes_home }}/ssl/key.pem" }


- name: Install Kube-Node Systemd Config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0640
  with_items:
  - { src: "kubelet.conf", dest: "{{ kubernetes_home }}/etc/kubelet.conf" }
  - { src: "kubelet.yaml", dest: "{{ kubernetes_home }}/etc/kubelet.yaml" }
  - { src: "kubelet.service.j2", dest: "/usr/lib/systemd/system/kubelet.service" }
  - { src: "config.toml", dest: "/etc/containerd/config.toml" }
  tags: nodefix


- name: Install Node Kubeconfig
  template:
    src: "node.kubeconfig"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0640
  with_items:
  - { dest: "{{ kubernetes_home }}/etc/kubelet-bootstrap.kubeconfig", context_user: "kubelet-bootstrap" }
  tags: nodefix


- name: Enable Kubernetes Node Service
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
  - 'containerd'
  - 'kubelet'
  tags: nodefix


- name: Copy Pause Image To Node
  copy:
    src: "{{role_path}}/files/pause-3.9-{{ansible_architecture}}.tar"
    dest: /tmp/

- name: Import Pause Image Into Containerd
  shell: |
    ctr -n k8s.io i import /tmp/pause-3.9-{{ansible_architecture}}.tar
    rm -f /tmp/pause-3.9-{{ansible_architecture}}.tar

