---

- name: Create Kubernetes Dirctory
  file:
    path: "{{ kubernetes_home }}/{{item}}"
    state: directory
    mode: 0755
    recurse: yes
    owner: root
    group: root
  with_items:
  - 'bin'
  - 'etc'
  - 'ssl'
  - 'logs'

- name: Create .kube Dirctory
  file:
    path: "/root/.kube"
    state: directory
    mode: 0755
    recurse: yes
    owner: root
    group: root

- name: Disable SWAP
  shell: swapoff -a


#### Kube-Master 安装 ####

- name: Install Kubernetes Control Plane
  import_tasks: kube-control.yml
  tags: control


#### Kube-Node 安装 ####

- name: Install Kubernetes Worker
  import_tasks: kube-worker.yml
  tags: worker


- name: Setting Kubernetes Cluster Alter Installed
  import_tasks: kube-setting.yml
  tags: setting
