REGISTRY: "reg.guideirai.online"
intellgent_sensing_cloud_web: reg.guideirai.online/universal/intellgent-sensing-cloud-web:tag_9c9056a5_1729080669_345
universal_addressbook: reg.guideirai.online/universal/universal-addressbook:tag_00f1a2de_1728527000_86
universal_advice: reg.guideirai.online/universal/universal-advice:tag_4d8ea911_1728730070_54
universal_algorithm: reg.guideirai.online/universal/universal-algorithm:tag_d512f7d3_1729132611_172
universal_cascade: reg.guideirai.online/universal/universal-cascade:tag_887b4866_1729002381_30
universal_device: reg.guideirai.online/universal/universal-device:tag_4f7233a7_1729084417_280
universal_event: reg.guideirai.online/universal/universal-event:tag_c46f6735_1729073904_610
#universal_gateway: reg.guideirai.online/universal/universal-gateway:tag_c0d7fdb1_1727348846_10
universal_gbcascade: reg.guideirai.online/universal/universal-gbcascade:tag_45e167f5_1728479570_26
universal_govern: reg.guideirai.online/universal/universal-govern:tag_068b0694_1729073459_381
universal_oauth: reg.guideirai.online/universal/universal-oauth:tag_2168f6e0_1728990665_149
universal_operatelog: reg.guideirai.online/universal/universal-operatelog:tag_12eaab5b_1728717811_40
universal_video: reg.guideirai.online/universal/universal-video:tag_24fdc454_1729078510_183
sensmart_auth: reg.guideirai.online/sensmart/sensmart-auth:tag_4b4885ff_1728957187_27
smart_ops: reg.guideirai.online/sensmart/smart-ops:tag_03090517_1730269241_124
sensmart_ops: reg.guideirai.online/sensmart/smart-ops:tag_03090517_1730269241_124
cbb_flow_engin: reg.guideirai.online/ops-test/cbb-flow-engin:20241024193004_asth66
cbb_msg_dispatcher: reg.guideirai.online/ops-test/cbb-msg-dispatcher:20241017095754_f5519l
commander: reg.guideirai.online/sensmart/commander:20
video_adapter: reg.guideirai.online/sensmart/video-adapter-service:tag_370074c5_1730344121_159
video_cascader: reg.guideirai.online/ops-test/video-cascader:20241017095725_bkm1ll
ai_platform_core: reg.guideirai.online/ai/ai-platform-core:tag_9d44ddc5_1729086616_97
ai_platform_dh: reg.guideirai.online/ai/ai-platform-dh:tag_d52f63b9_1728631310_43
ai_platform_distance: reg.guideirai.online/ai/ai-platform-distance:tag_b80e2746_1729514272_81

# 项目域名
universal_web_domain: universal-web.guideirai.online

# PAAS平台地址
# https://10.10.82.10:8320
cloud_pass: https://192.168.18.31:8320

# 省政务外网IP
universal_web_sheng_ip: '59.208.0.97'
# 市政务外网IP
universal_web_shi_ip: '10.13.30.125'
# paas内网IP
paas_inner_ip: '172.23.86.36' 

# minio地址
# http://minio-videocollect-shi-test.guideirai.online:39000
minio_host: 64.97.155.195:8060