apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-ops
  namespace: sensmart
  labels:
    app: smart-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-ops
  template:
    metadata:
      labels:
        app: smart-ops
    spec:
      containers:
      - name: smart-ops
        image: {{sensmart_ops}}
        ports:
        - name: server
          containerPort: 10522
          protocol: TCP
        - name: grpc-tri
          containerPort: 10521
          protocol: TCP
        - name: debug
          containerPort: 10523
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 10522
          initialDelaySeconds: 300 
          timeoutSeconds: 10   
          periodSeconds: 60
          failureThreshold: 10 
        livenessProbe:
          tcpSocket:
            port: 10522
          initialDelaySeconds: 300 
          timeoutSeconds: 10   
          periodSeconds: 60
          failureThreshold: 10
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: JVM
            value: '1024'
          - name: JVM_CUSTOM
            value: ' -Denv=TEST -Dfile.encoding=utf-8 -Dspring.cloud.nacos.config.file-extension=properties -Dspring.cloud.nacos.config.server-addr=nacos.public.svc.cluster.local:8848 -Dspring.cloud.nacos.config.username=nacos -Dspring.cloud.nacos.config.password=nacos -Dspring.cloud.nacos.discovery.server-addr=nacos.public.svc.cluster.local:8848 -Dspring.cloud.nacos.discovery.username=nacos -Dspring.cloud.nacos.discovery.password=nacos --add-opens=java.management/sun.management=ALL-UNNAMED --add-opens=java.base/sun.net=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.math=ALL-UNNAMED --add-opens=java.base/jdk.internal.misc=ALL-UNNAMED -XX:+UnlockExperimentalVMOptions -XX:MaxRAM=1G -XX:InitialRAMPercentage=10 -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=70 -Xms512m -Xmx1024m -server -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:10523'
          - name: TZ
            value: Asia/Shanghai
          - name: APP_NAME
            value: sensmart-ops
          - name: LANG
            value: en_US.UTF-8
          - name: PROJECT_NAME
            value: sensmart-ops
          - name: WEBPORT
            value: '10522'
          - name: isolate
            value: video-sheng
          - name: LOG_KAFKA_REGION
            value: e30=
          - name: SENTINEL_URL
            value: '-'
          - name: CODE_VERSION
            value: '17'
          - name: DUBBO_ENV_KEYS
            value: zone,isolate
          - name: JVMMN
            value: '512'
          - name: ISKUBERAPP
            value: 'true'
          - name: CONFIG_ENV
            value: TEST
        resources:
            requests:
              memory: "2000Mi"
              cpu: "1"
            limits:
              memory: "2000Mi"
              cpu: "1"
        volumeMounts:
          - mountPath: /opt/logs
            name: smart-ops-log
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: smart-ops-log
          emptyDir:
            sizeLimit: 1Gi

--- 
# 服务本身 nodeport
apiVersion: v1
kind: Service
metadata:
  name: smart-ops-svc-nodeport
  namespace: sensmart
spec:
  ports:
    - protocol: TCP
      port: 10522
      targetPort: 10522
      nodePort: 20522
  selector:
    app: smart-ops
  type: NodePort