---

- name: Create CA CSR File
  ansible.builtin.copy:
    src: root-csr.json
    dest: /tmp/ca/
  when: inventory_hostname in groups['control']

- name: Generate Root CA
  ansible.builtin.shell: |
    cfssl gencert -initca root-csr.json |cfssljson -bare ca
  args:
    chdir: /tmp/ca
  when: inventory_hostname in groups['control']