---

- name: Downloading Helm {{ helm_version }}
  ansible.builtin.get_url:
    url: "{{ helm_download_url_prefix }}/helm-{{ helm_version }}-linux-{{ arch_alias }}.tar.gz"
    dest: "{{ component_path }}/helm-{{ helm_version }}-linux-{{ arch_alias }}.tar.gz"
    mode: '0755'
    timeout: 60
  # amazon.aws.s3_object:
  #   endpoint_url: "{{ s3_endpoint_url }}"
  #   access_key: "{{ s3_access_key }}"
  #   secret_key: "{{ s3_secret_key }}"
  #   bucket: "{{ s3_bucket_name }}"
  #   object: "helm/{{ helm_version }}/linux/{{ arch_alias }}/helm-{{ helm_version }}-linux-{{ arch_alias }}.tar.gz"
  #   dest: "{{ component_path }}/helm-{{ helm_version }}-linux-{{ arch_alias }}.tar.gz"
  #   mode: get
  #   overwrite: different
  delegate_to: localhost
  run_once: true
  retries: 5
  delay: 10
  when: helm_stat.stat.exists == false and method == 'online'

- name: Copy Helm {{ helm_version }} Binary To Remote Host
  ansible.builtin.copy:
    src:  "{{ component_path }}/helm-{{ helm_version }}-linux-{{ arch_alias }}.tar.gz"
    dest: "/tmp/helm-{{ helm_version }}-linux-{{ arch_alias }}.tar.gz"

- name: Install Helm Binary On Remote Host
  uncompress:
    src:  "/tmp/helm-{{ helm_version }}-linux-{{ arch_alias }}.tar.gz"
    dest: /usr/local/bin/
    mode: '0755'
    strip_components: 1
    include:
      - helm