---

- name: Approve node sign request
  shell: |
    for csr in $(kubectl get csr|grep 'Pending'|awk '{print $1}'); do
      kubectl certificate approve $csr
    done

- name: Taint master
  shell: |
    kubectl taint nodes "{{ inventory_hostname }}" node-role.kubernetes.io/master=:NoSchedule
  when: allow_master_schedule != true

- name: Label Control Plane
  shell: |
    kubectl label nodes "{{ inventory_hostname }}" node-role.kubernetes.io/control-plane=

- name: Install CNI Plugin
  ansible.builtin.include_role:
    name: "{{ cni_plugin }}"