
kube_pod_infra_image: 'registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.9'
kube_pause_image: "{{ registry_mirror.get('registry.k8s.io', 'registry.k8s.io') }}/pause:3.9"
containerd_image_mirror: 'https://253dmx7q.mirror.aliyuncs.com'

cri_kernel_params:
  - { name: net.bridge.bridge-nf-call-iptables, value: 1 }
  - { name: net.ipv4.ip_forward, value: 1 }
  - { name: net.bridge.bridge-nf-call-ip6tables, value: 1 }

kube_download_url_prefix: 'https://dl.k8s.io'
containerd_download_url_prefix: 'https://github.com/containerd/containerd/releases/download'
runc_download_url_prefix: 'https://github.com/opencontainers/runc/releases/download'
cni_plugin_download_url_prefix: 'https://github.com/containernetworking/plugins/releases/download'